name: Build and Deploy Docs
on:
  push:
    branches:
      - main
jobs:
  deploy:
    strategy:
        matrix:
          python-version: [ 3.8 ]
          os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install \
              mkdocs-material \
              mkdocstrings[python] \
              mknotebooks \
              pymdown-extensions
      - run: mkdocs gh-deploy --force
